### ISSUE TITLE
Add callbacks

### ISSUE THREAD

**Issue by moteus** [Lua-cURL/Lua-cURLv3#103]
* [x] Seek
 * [x] Debug
 * [x] Match
 * [x] Chunk begin
 * [x] Chunk end

**Comment by data-man** [comment]
Please, add fnmatch & debug callbacks also.

**Comment by moteus** [comment]
@data-man Please can you test #104

**Comment by data-man** [comment]
@moteus 

> Also may be worth swap arguments in fnmatch callback to match(string, pattern)?

Ideally!

**Comment by moteus** [comment]
I think it not very good idea. because usially we need not regexp. e.g. in url `ftp:///..../test.*`.
In this case `string.find` will also accept e.g. `mytestfile.txt` which is not very obvious.
So I think better write your own function to handle it and string.find is not good alternative.
Also to work with it need `CURLOPT_CHUNK_BGN_FUNCTION` and `CURLOPT_CHUNK_END_FUNCTION`
