### ISSUE TITLE
failed compile on mac

### ISSUE THREAD

**Issue by zhaozg** [Lua-cURL/Lua-cURLv3#112]
make CFLAGS=-I/usr/local/lua
```
6 warnings generated.
src/lchttppost.c:119:12: warning: unused function 'lcurl_hpost_to_s' [-Wunused-function]
static int lcurl_hpost_to_s(lua_State *L){
           ^
1 warning generated.
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lcurl.so] Error 1
bash-3.2$ uname -a
Darwin MacBook-Air 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
bash-3.2$ 
```

**Comment by moteus** [comment]
First warning already solved on master. When I implement this function I take a breake to think is it should
be used to convert form to string or use `get` method instead. :)

About second one. I do not maintain this makefile. But problem is pretty obvious.
You do not need link with real time library on OSX. In fact I do not think it is needed
to link with it at all. Rockspec does not do it. May be it required if using static version
of libcurl? So PR are welcome.

@msva ping

**Comment by msva** [comment]
Well, actually I have no working MacOS X at this moment, so I can't properly test for the fix, but I can indeed drop linking against `librt` just in case.
I'll try to look into in today's evening.

**Comment by moteus** [comment]
@zhaozg can you please checkout current master

**Comment by zhaozg** [comment]
Fixed
