### ISSUE TITLE
headerfunction example to process header before body download?

### ISSUE THREAD

**Issue by nutinshell** [Lua-cURL/Lua-cURLv3#116]
How can I use `headerfunction` to only download text/html content_type file, other content_type abort? Thanks.

**Comment by moteus** [comment]
I think you just can return `false` value to abort request.
In this case callback will return 0 and according [documentation](https://curl.haxx.se/libcurl/c/CURLOPT_HEADERFUNCTION.html) request should be interrupded.
PS. In fact you can return nil or number and this value will be translated as result for callback.
https://github.com/Lua-cURL/Lua-cURLv3/blob/master/src/lceasy.c#L970

**Comment by moteus** [comment]
There exists [test case](https://github.com/Lua-cURL/Lua-cURLv3/blob/master/test/test_easy.lua#L343-L352) for that
```Lua
  c = curl.easy{
    url = GET_URL;
    writefunction = dummy,
    headerfunction = function(str) return false end;
  }
```

PR with simple example are welcome.
