### ISSUE TITLE
Initializing httppost when creating object

### ISSUE THREAD

**Issue by softwarefailure** [Lua-cURL/Lua-cURLv3#118]
In the `post_form.lua` example we can see the following code:

```
  httppost = cURL.form{

    -- file form filesystem
    name01 = {
      file = "post_form.lua",
      type = "text/plain",
      name = "post.lua",
    },

    -- file form string
    name02 = {
      data = "<html><bold>bold</bold></html>",
      name = "dummy.html",
      type = "text/html",
    },

    -- file form stream object
    name03 = {
      stream  = Stream:new('8', 25),
      name    = "stream1.txt",
      type    = "text/plain",
      headers = {
        "X-Test-Char : 8",
        "X-Test-length : 25",
      }
    },

    -- file form stream function
    name04 = {
      stream  = stream,
      length  = length,
      name    = "stream2.txt",
      type    = "text/plain",
    },

  }, 
```

But is this really still supported? I don't see anything in the source code that could handle such code. Instead, it looks like form objects have to be filled using `add_content`, `add_file`, etc. 

So if this example is a leftover from Lua-cURLv2, please delete it... (and also adapt the doc)

**Comment by moteus** [comment]
This is [cURLv3 API](https://github.com/Lua-cURL/Lua-cURLv3/blob/master/src/lua/cURL/impl/cURL.lua#L162) I think. This API is Lua wrapper around lcurl C API. 
There exists new MIME API wich cURL recomendet use instead of this HTTP API.
But I have no time to implement it now. In fact I start implement it but can not create good Lua API.

**Comment by softwarefailure** [comment]
Right, I didn't know that there was an additional Lua wrapper around the library. Then it makes sense. The MIME API would be nice to have as well.
