### ISSUE TITLE
undefined symbol: lcurl_mime_set_lua

### ISSUE THREAD

**Issue by t-k-** [Lua-cURL/Lua-cURLv3#128]
my hello.lua file:
```lua
local cURL = require("cURL")
```

When I try to run `lua hello.lua`, it has error:
```
lua: error loading module 'lcurl' from file '/home/tk/.luarocks/lib/lua/5.3/lcurl.so':
        /home/tk/.luarocks/lib/lua/5.3/lcurl.so: undefined symbol: lcurl_mime_set_lua
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        /home/tk/.luarocks/share/lua/5.3/cURL.lua:11: in main chunk
        [C]: in function 'require'
        hello.lua:12: in main chunk
        [C]: in ?
```

My lua-curl package is installed from `luarocks install --local lua-curl`

My environment:
LuaRocks 2.4.4
Lua version: 5.3

**Comment by moteus** [comment]
Thanks for reporting.
This is bug in the last rockspec
Please install 0.3.7 version
I'll fix it today or tomorrow

**Comment by moteus** [comment]
I upload new rockspec file.
Please try reinstall latest version (0.3.8-2)

**Comment by t-k-** [comment]
Yes, it is working now. Thank you!
