### ISSUE TITLE
Error loading module lcurl on Lubuntu 18.04 with version 0.3.8-1

### ISSUE THREAD

**Issue by Bagfields** [Lua-cURL/Lua-cURLv3#129]
/usr/bin/lua: error loading module 'lcurl' from file '/usr/local/lib/lua/5.2/lcurl.so':
	/usr/local/lib/lua/5.2/lcurl.so: undefined symbol: lcurl_mime_set_lua
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/lua/5.2/cURL.lua:11: in main chunk
	[C]: in function 'require'

64 bit system

**Comment by moteus** [comment]
Tthere was bug in this rockspec
Try use.3.8-2.
Wre do you get 0.3.8-1 version
I remove it after few days after release

**Comment by Bagfields** [comment]
Installed it shortly after 18.04 came out but didn't use it until today.
Thanks 
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2018-06-21, 22:49 Alexey Melnichuk <notifications@github.com> wrote:
Tthere was bug in this rockspec
Try use.3.8-2.
Wre do you get 0.3.8-1 version
I remove it after few days after release

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Lua-cURL/Lua-cURLv3/issues/129#issuecomment-399238913","url":"https://github.com/Lua-cURL/Lua-cURLv3/issues/129#issuecomment-399238913","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Lua-cURL/Lua-cURLv3","title":"Lua-cURL/Lua-cURLv3","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Lua-cURL/Lua-cURLv3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@moteus in #129: Tthere was bug in this rockspec\r\nTry use.3.8-2.\r\nWre do you get 0.3.8-1 version\r\nI remove it after few days after release "}],"action":{"name":"View Issue","url":"https://github.com/Lua-cURL/Lua-cURLv3/issues/129#issuecomment-399238913"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Lua-cURL/Lua-cURLv3] Error loading module lcurl on Lubuntu 18.04 with version 0.3.8-1 (#129)",
"sections": [
{
"text": "",
"activityTitle": "**Alexey Melnichuk**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@moteus",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Lua-cURL/Lua-cURLv3\",\n\"issueId\": 129,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Lua-cURL/Lua-cURLv3\",\n\"issueId\": 129\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Lua-cURL/Lua-cURLv3/issues/129#issuecomment-399238913"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 348724281\n}"
}
],
"themeColor": "26292E"
}
