### ISSUE TITLE
Running the script post_mime.lua  Error

### ISSUE THREAD

**Issue by EnigmaHong** [Lua-cURL/Lua-cURLv3#132]
When i running post_mime.lua ，there is a erroe: post_mime.lua:8: attempt to call method 'mime' (a nil value) . What should I do to solve this problem,thank.

ubuntu@4D:~/Lua-cURLv3-master/examples/cURLv3$ qlua post_mime.lua 
qlua: post_mime.lua:8: attempt to call method 'mime' (a nil value)
stack traceback:
	[C]: in function 'mime'
	post_mime.lua:8: in main chunk

**Comment by moteus** [comment]
This example should work with lua-curl >= 0.3.8 which compiled with libcurl >= 7.56.0

**Comment by EnigmaHong** [comment]
The problem has been solved.Thank you,
