### ISSUE TITLE
Unable to compile lcerror.c

### ISSUE THREAD

**Issue by nembsbe** [Lua-cURL/Lua-cURLv3#134]
gcc -O2 -fPIC -I/home/kyson/workspace/devlop/release/sdk/ar71xx/staging_dir/hostpkg/include -c src/lcerror.c -o src/lcerror.o -I/mnt/sda1/install/lua-5.1.5/src
src/lcerr_easy.h: In function 'lcurl_err_easy_mnemo':
src/lcerror.c:32:22: error: duplicate case value
 #define ERR_ENTRY(E) case CURLE_##E: return #E;
                      ^
src/lcerr_easy.h:74:1: note: in expansion of macro 'ERR_ENTRY'
 ERR_ENTRY ( SSL_CACERT               )
 ^
src/lcerror.c:32:22: error: previously used here
 #define ERR_ENTRY(E) case CURLE_##E: return #E;
                      ^
src/lcerr_easy.h:65:1: note: in expansion of macro 'ERR_ENTRY'
 ERR_ENTRY ( PEER_FAILED_VERIFICATION )
 ^

Please can someone help?

**Comment by moteus** [comment]
What version of libcurl you use?

According [docs](https://curl.haxx.se/libcurl/c/libcurl-errors.html) and source code [CURE_PEER_FAILED_VERIFICATION](https://github.com/curl/curl/blob/f762fec323f36fd7da7ad6eddfbbae940ec3229e/include/curl/curl.h#L520) and [CURLE_SSL_CACERT](https://github.com/curl/curl/blob/f762fec323f36fd7da7ad6eddfbbae940ec3229e/include/curl/curl.h#L531) have to have different values

But as quick fix you can try comment out one of this values in lcerr_easy.h file.

**Comment by nembsbe** [comment]
How can I check the version of libcurl?  I’m sure I have libcurl.so.4 if that helps?

**Comment by moteus** [comment]
You can checkout `curl/curl.h` to find out what values assigned to these error codes
Also you can checkout  and  [curl/curlver.h](https://github.com/curl/curl/blob/master/include/curl/curlver.h#L33) file to find out libcurl version.

**Comment by nembsbe** [comment]
Thank you that helped so much.  I have this one working now.
