### ISSUE TITLE
Could you please update it to support arm64e for A12/A12X?

### ISSUE THREAD

**Issue by kentkrantz** [Lua-cURL/Lua-cURLv3#147]
Thank you!

**Comment by moteus** [comment]
What problems do you have?
This is q stragghforward C code an should be quite portable.
Its compiled on osx with gcc on the Travis ci.
May be need to add clang as whell

**Comment by kentkrantz** [comment]
I added `arm64e` to the `ARCH` list, compiled and run on iOS but got error symbol "_BIO_f_ssl" and "_ASN1_STRING_free" not found.

**Comment by moteus** [comment]
This seems questions for the libcurl.
Or using correct headers
