### ISSUE TITLE
Support of LuaJit lateset version and "writefunction" -> variable

### ISSUE THREAD

**Issue by GildedHonour** [Lua-cURL/Lua-cURLv3#150]
1. Does is support LuaJit 2.0.5 or 2.1 beta?

2. If it does, how do I use the `writefunction` to save returned binary data in a variable? In the documentation it uses `writefunction`  to write a result into a file.

Whereas I want to fetch an image and save its binary data into a Lua variable. Not a file

**Comment by GildedHonour** [comment]
```
$ luajit
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> local cURL = require "cURL"
error loading module 'lcurl' from file '/usr/lib/lua/5.3/lcurl.so':
	/usr/lib/lua/5.3/lcurl.so: undefined symbol: lua_absindex
stack traceback:
	[C]: at 0x5640b3e5cfb0
	[C]: in function 'require'
	/usr/share/lua/5.3/cURL.lua:11: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: at 0x5640b3e0dc00

```

**Comment by moteus** [comment]
It works and tested with all Lua versions https://github.com/Lua-cURL/Lua-cURLv3/blob/master/.travis.yml#L12 and https://github.com/Lua-cURL/Lua-cURLv3/blob/master/appveyor.yml#L13.

Simple way to use `writefunction` is just `buffer = {}, easy:setopt_writefunction(table.insert, buffer)`

`lua_absindex` added in Lua 5.2. You have to compile lcurl.so file with correct headers. Lua does not support ABI/API compatibility between minor versions.
