### ISSUE TITLE
undefined symbol: lcurl_mime_set_lua

### ISSUE THREAD

**Issue by thewinelake** [Lua-cURL/Lua-cURLv3#152]
This might be a repeat, but I'm getting the same as #128. 
I'm installing with /usr/local/bin/luarocks install Lua-cURL  CURL_INCDIR=/usr/include/x86_64-linux-gnu  --server=https://luarocks.org/dev

Version is scm-0 - so I don't quite understand why that's not numeric!

Thanks

**Comment by thewinelake** [comment]
I've fixed this by downloading 0.3.9

**Comment by moteus** [comment]
This is because I did not update scm version in the LuaRocks repo. 
Thanks for the report. I'll going make small bugfix and also update it in this week.

**Comment by moteus** [comment]
Just pushed a new version (0.3.11) to the LuaRocks.
Also, I update scm rockspec file there.
