### ISSUE TITLE
Help with NTLM authentication

### ISSUE THREAD

**Issue by rnalrd** [Lua-cURL/Lua-cURLv3#155]
Hi,

I'm trying to get NTLM authentication to work:

<pre>
local cURL = require "cURL"

local URLtest = "http://local.site/search"
local user = "testuser:password"

local c = cURL.easy() 

c:setopt {
  url = URLtest,
  post = true,
  writefunction = io.write,
  username = user,
  postfields = '{}',
--  httpauth = true,
  [cURL.AUTH_NTLM] = true
}

c:perform():close()
</pre>

The output is:

`/usr/bin/lua5.3: [CURL-EASY][UNKNOWN_OPTION] An unknown option was passed in to libcurl (48)`

If I change the last option to:

`[cURL.NTLM] = true`

the error is:

`/usr/bin/lua5.3: ./ntlmtest:17: table index is nil`

I'm currently using version 0.3.8.

I could not find any documentation or examples about using NTLM authentication. _httpauth_ seems to turn on just Basic auth.

Thanks for your help!

**Comment by moteus** [comment]
I think you have to set [CURLOPT_HTTPAUTH](https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html) option.
`httpauth = curl.AUTH_NTLM`
May be you need to set passwd option as whell

**Comment by rnalrd** [comment]
In my earlier tests with _httpauth_ it seemed that it accepted only boolean values. 

Anyway now it works, thanks!
