### ISSUE TITLE
implementing PUT method

### ISSUE THREAD

**Issue by eamgit892** [Lua-cURL/Lua-cURLv3#156]
Hello, I've looked through the code and did not found implementation for the PUT method. Is it possible with existing code?, maybe manipulating with opt_fields, wrapping some method to a new function? Pls advise the approach

**Comment by csaar95** [comment]
Yes it's possible. You have to build the methods for ur own.

For instance an excerpt from my implementation:
```lua
[...]
  elseif (
    (method == 'POST') or (method == 'PUT') or (method == 'PATCH') or
    (method == 'TRACE') or (method == 'OPTIONS') or (method == 'DELETE')
  ) then
    c:setopt{
      [cURL.OPT_CUSTOMREQUEST] = method -- custom method
    }
    if body and body.type and body.contents then
      headers['Content-Type'] = tostring(body.type)
      c:setopt{
        [cURL.OPT_POSTFIELDS] = tostring(body.contents)
      }
    end
[...]
```

**Comment by eamgit892** [comment]
Thank you!
