### ISSUE TITLE
Move Lua-cURLv2 compatibility layer into separate file

### ISSUE THREAD

**Issue by cryi** [Lua-cURL/Lua-cURLv3#174]
Hi, 

I wonder whether it is possible to move `Load_cURLv2` and load it through `pcall(require, ...)` or some alternative way. 

For my use case compatibility layer is not necessary and I would like to drop it out of my built pipeline. For that I need it to be separate file and making it loaded only if available. I am ready to make this change just want to make sure it would be accepted as PR.

Please let me know.

**Comment by msva** [comment]
As far as it wouldn't brake backward cmpatibility, chances for PR to be accepted are high (although, I can't guarantee the time: I'm very busy at work, and can't say anything about @moteus spare time)

**Comment by cryi** [comment]
OK I ll try look into that when I get some time.

**Comment by moteus** [comment]
I have no statistic about usage of this API.
May be start maintain `lcurl` module, but need to figure out a new name for compatability.
In fact C module is enouth in most cases
