### ISSUE TITLE
MacOS Installation Error

### ISSUE THREAD

**Issue by PrateekGoyal18** [Lua-cURL/Lua-cURLv3#175]
`luarocks install Lua-cURL`
Installing https://luarocks.org/lua-curl-0.3.13-1.src.rock
Error: Could not find header file for CURL
  No file curl/curl.h in /usr/local/include
  No file curl/curl.h in /usr/include
  No file curl/curl.h in /include
You may have to install CURL in your system and/or pass CURL_DIR or CURL_INCDIR to the luarocks command.
Example: luarocks install lua-curl CURL_DIR=/usr/local

**PS - curl is installed in the system**
`curl --version`
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

**Comment by moteus** [comment]
to be able to build C library you also have to install header files.
Not sure what is the right way on a MacOS

**Comment by dauuricus** [comment]
same issue but on **chromebook** arm.

solution (my case on Crostini):
https://imgur.com/a/Xb1bG8l

* install libcurl4-gnutls-dev from package manager (not luarocks; my case: APT )

```
apt search libcurl4
``` 

```
sudo apt-get install libcurl4-gnutls-dev
```

* find curl.h path
```
find /usr/ | grep curl.h
find /usr/ | grep libcurl
```

* install Lua-cURL by luarocks with path

example:

```
sudo luarocks install Lua-cURL CURL_INCDIR=/usr/include/aarch64-linux-gnu/
```
