### ISSUE TITLE
[Doubt] Luacurl to localhost Flask Server

### ISSUE THREAD

**Issue by atibdialpad** [Lua-cURL/Lua-cURLv3#177]
Could not find any luacurl discussion channel so using this issue.

I have a python flask server running on my machine. I need to to talk to this flask server from lua code. Can I use luacurl for this, url like "http://127.0.0.1:port/api/<xyz>"

When I run curl to this url, it works :
curl https://127.0.0.1:8082/api/code_version/ --insecure

could it be because of the "--insecure" arg ? How do I pass it to  luacurl ?

**Comment by atibdialpad** [comment]
I tried with  c:setopt(curl.OPT_SSL_VERIFYPEER, false), no luck

**Comment by cryi** [comment]
Hi @atibdialpad,

it should work. Show us whole snippet. This is [how I use it in REST client](https://github.com/cryon-io/eli/blob/master/lib/eli/net.lua#L61-L74). Although I do not test this in test suite so I am not sure. But it worked when I tested manually iirc.

**Comment by moteus** [comment]
This should work
```Lua
c = cURL.easy{
  url            = 'https://127.0.0.1:8082/api/code_version/',
  ssl_verifypeer = false,
  ssl_verifyhost = false,
  ....
}
c:perform()
```

PS. with the curl command line util you can use `--libcurl`  argument to check out all options used in this command
