### ISSUE TITLE
Unable to protect a lua stack trace if server is not available

### ISSUE THREAD

**Issue by feckert** [Lua-cURL/Lua-cURLv3#181]
lua-cURL: 0.3.13
curl 7.79.1 (x86_64-openwrt-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1l

I want to send a JSON object to a server with the following small lua script:

```
#!/usr/bin/env lua
local curl = require("cURL")

local easy = curl.easy()
easy:setopt{
  url = "http://192.168.0.2:2000/test/123456789012345",
  post = true,
  httpheader =  {'Content-Type:application/json', 'Accept: application/json', 'Connection: close'},
  postfields = '{"type" = "stats",  "version" = "1.0.0"}'
}

local ok, err = easy:perform()
```
If the server is not running I get the following error:

```
root@st-dev-07 ~ # ./test.lua
lua: [CURL-EASY][COULDNT_CONNECT] Error (7)
stack traceback:
        [C]: in function '?'
        /usr/lib/lua/cURL/impl/cURL.lua:31: in function </usr/lib/lua/cURL/impl/cURL.lua:30>
        (tail call): ?
        ./test.lua:12: in main chunk
        [C]: ?
```

The program terminates here with an error.
How can I intercept this so that the script does not do a `stack traceback`?
Later I would like to run this part of the script in a service loop to send some data every hour to a backend.
It would not be nice if the service stops working just because the backend where it is supposed to store the data is not running.
 
Test server:
`echo -e "HTTP/1.1 200 OK\r\nContent-Length:0\r\n\r\n" | nc -l -p 2000`

**Comment by moteus** [comment]
you can use the `cURL.safe` mudule

**Comment by msva** [comment]
alternatively, you can use
```lua
ok, err = pcall(easy.perform,easy)
```
