### ISSUE TITLE
Upper case module name issue

### ISSUE THREAD

**Issue by stepelu** [Lua-cURL/Lua-cURLv3#55]
Would it be possible to rename `cURL` to `curl` in the `require()` calls and filenames?
As some OS are case sensitive wrt filenames and some are not this results in system-dependent behaviour. It's also less confusing to have everything lowercase, it's the common practice for Lua modules, and it makes life easier for writers of package managers.

**Comment by moteus** [comment]
Module always names as `cURL` so to compatiable with existed code it should stay as is.
May be we can add some basic file `curl.lua`:
```Lua
return require 'cURL'
```
And insall this file only on needed platforms. But I do not know how to check such platforms (Any non Windows?)

**Comment by stepelu** [comment]
I am not sure this would be a good solution. If the name cannot be changed probably it's best to leave the situation as it is.
