### ISSUE TITLE
How can I catch timeout?

### ISSUE THREAD

**Issue by tapir** [Lua-cURL/Lua-cURLv3#61]
When I try to download a big file I get this: lua: [OPERATION_TIMEDOUT] Timeout was reached (28)
But the execution of the function stops right away. I want to be able to handle this error? How can I do it?

**Comment by moteus** [comment]
Sorry. I miss this somehow. I think it possible set `CURLOPT_TIMEOUT` option.
I am not sure it possible `resume` operation when you already get this error.
