### ISSUE TITLE
curl.PROXY_SOCKS5_HOSTNAME [UNKNOWN_OPTION]

### ISSUE THREAD

**Issue by aryajur** [Lua-cURL/Lua-cURLv3#72]
Hi I was trying out the PROXY_SOCKS5_HOSTNAME option and it gives an error saying it is an [UNKNOWN_OPTION].

    c:setopt(curl.PROXY_SOCKS5_HOSTNAME,"localhost:PORTNUM")

**Comment by moteus** [comment]
`curl.PROXY_SOCKS5_HOSTNAME` Is not option name is option value for [CURLOPT_PROXY](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html).
So you can use it like `c:setopt(curl.OPT_PROXY, curl.PROXY_SOCKS5_HOSTNAME)`

PS. All option names start with `OPT_` prefix

**Comment by aryajur** [comment]
Thanks for the explanation. Is there a way I can see the list of all the accepted options or all the options in the Curl manual are accepted?

**Comment by moteus** [comment]
You can check [curl manual](https://curl.haxx.se/libcurl/c/easy_setopt_options.html).

**Comment by aryajur** [comment]
Thank you very much.
