### ISSUE TITLE
How can I set ssl key passwd?

### ISSUE THREAD

**Issue by barabaspeter** [Lua-cURL/Lua-cURLv3#75]
I merged my key and cert pem files into one file for apple push notification. I want to set the password for the key, but i cannot find setopt_sslkeypasswd.
Is is missing or is there any other way to do this?

**Comment by moteus** [comment]
I think I miss this one. I think I add it today or tomorrow. Or you can make PR.
I think it just one line [like this](https://github.com/Lua-cURL/Lua-cURLv3/blob/8aa9f702b7b65222bdb41f50f425adfbf1030f94/src/lcopteasy.h#L227)

**Comment by barabaspeter** [comment]
Thanks a lot.
