### ISSUE TITLE
install error typedef‘lcurl_multi_t’

### ISSUE THREAD

**Issue by hicancer** [Lua-cURL/Lua-cURLv3#85]
why my install is error?
[root@lua bin]# ./luarocks install Lua-cURL --server=https://rocks.moonscript.org/dev
Installing https://rocks.moonscript.org/dev/lua-curl-scm-0.rockspec
gcc -O2 -fPIC -I/www/wdlinux/openresty/luajit/include/luajit-2.1 -c src/l52util.c -o src/l52util.o -I/usr/include
gcc -O2 -fPIC -I/www/wdlinux/openresty/luajit/include/luajit-2.1 -c src/lceasy.c -o src/lceasy.o -I/usr/include
In file included from src/lceasy.c:17:
src/lcmulti.h:24: 错误：typedef‘lcurl_multi_t’重定义
src/lceasy.h:38: 附注：‘lcurl_multi_t’的上一个声明在此

Error: Build error: Failed compiling object src/lceasy.o
[root@lua bin]#

**Comment by james-leo** [comment]
I have meet the same problem, give the err in the english edition CentOS release 6.7 (Final)

[root@localhost software]# luarocks install lua-curl 
Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/lua-curl-0.3.5-1.src.rock
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/l52util.c -o src/l52util.o -I/usr/include
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/lceasy.c -o src/lceasy.o -I/usr/include
In file included from src/lceasy.c:17:
src/lcmulti.h:24: error: redefinition of typedef ‘lcurl_multi_t’
src/lceasy.h:38: note: previous declaration of ‘lcurl_multi_t’ was here

Error: Build error: Failed compiling object src/lceasy.o

**Comment by moteus** [comment]
I suppose you use gcc < 4.6.0.

Can you test replace this `typedef` in `lceasy.h` to `struct lcurl_multi_tag;`
and replace `lcurl_multi_t *multi;` to `struct lcurl_multi_tag *multi;` in struct defenition.

**Comment by james-leo** [comment]
@moteus  I have update gcc g++ 4.8.2 the other problem occurs , not found the error about file,
 change the other machine use luarocks gcc,g++ remains 4.4, repeat 'redefinition of typedef ‘lcurl_multi_t’  
 git clone the source then make it,the problem occurs again on the src/lcmulti.h:24: error: redefinition of typedef ‘lcurl_multi_t’ ,
del the 'lcurl_multi_t' on the 24 row
remake it , bingo .got lcurl.so

**Comment by moteus** [comment]
Please. Can you test #88

**Comment by stanleyxu2005** [comment]
I met the same issue while using `luarocks install Lua-cURL`. However when I let luarocks build again the master branch, it works.
