### ISSUE TITLE
Can I install as Portable edition?

### ISSUE THREAD

**Issue by stanleyxu2005** [Lua-cURL/Lua-cURLv3#91]
My current environment does not allow me to install luarocks etc. I'd like to download required modules and then put them into a `inlcude` dir. Is it possible?

**Comment by moteus** [comment]
if you want embed lua-curl to some host app then you can  add all *.c/*.h files.
Of course you also need libcurl themself.
 All function has `lcurl_XXX` prefix and all macros `LCURL_` one, so there should not
be problem with name collision.

**Comment by stanleyxu2005** [comment]
Actually the travis build for Lua 5.1 does everything I want. But my environment does not have all these tools and I'm not allowed to install any of them. I just want to download some prebuilt luacurl-lua5.1 for Linux

**Comment by moteus** [comment]
Sorry. I have no any prebuild binaries. I know Lua-cURL distribute as Pacakge in some repo.
Try this one http://repology.org/metapackage/lua:curl/packages.
I am work on Windows system only and just run tests on Linux.
Also you can try do compile you own binaries on different machine.

**Comment by stanleyxu2005** [comment]
Finally I build it very quick with a centos VM at home.
