### ISSUE TITLE
failed installing in FreeBSD with luarocks

### ISSUE THREAD

**Issue by webching** [Lua-cURL/Lua-cURLv3#98]
# luarocks-5.1 install Lua-cURL
..
..
cc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/l52util.c -o src/l52util.o -I/usr/local/include
Data segment size exceeds process limit

Error: Build error: Failed compiling object src/l52util.o

**Comment by moteus** [comment]
Sorry but I have not expirience on FreeBSD at all.
Does it compile or system error?
Do you have fix for this?
